version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gachdong
      MYSQL_USER: gachdong
      MYSQL_PASSWORD: gachdong123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  api-gateway:
    image: api-gateway-local
    container_name: api-gateway
    ports:
      - "8080:8080" # 외부에 노출될 포트
    depends_on:
      - club-service
    networks:
      - my-network

  club-service:
    image: club-service-local
    container_name: club-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_URL: jdbc:mysql://mysql:3306/gachdong
      MYSQL_USERNAME: gachdong
      MYSQL_PASSWORD: gachdong123
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
